export const COMPANY_USERS_DATA_LOADING = "COMPANY_USERS_DATA_LOADING";
export const COMPANY_USERS_DATA_SUCCESS = "COMPANY_USERS_DATA_SUCCESS";
export const COMPANY_USERS_DATA_FAILED = "COMPANY_USERS_DATA_FAILED";


export const TASKS_DATA_LOADING="TASKS_DATA_LOADING"
export const TASKS_DATA_SUCCESS="TASKS_DATA_SUCCESS"
export const TASKS_DATA_FAILED="TASKS_DATA_FAILED"

export const SELECT_SINGLE_TASK="SELECT_SINGLE_TASK"


export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
